[package]
name = "duifene-gui"
version.workspace = true
edition.workspace = true

[dependencies]
duifene-core = { path = "../duifene-core" }
gpui-kit = "0.6"
chrono = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }

[build-dependencies]
embed-resource = "3"
ico = "0.4"
resvg = "0.46"
tiny-skia = "0.11"

[dev-dependencies]
gpui-kit = { version = "0.6", features = ["test-support"] }
